### ISSUE TITLE
make install-dev may cause a numpy version mismacth.

### ISSUE THREAD

**Issue by lijiajun3029** [kscalelabs/sim#123]
`make install-dev
`output:
> INFO: pip is looking at multiple versions of kscale-sim-library[dev] to determine which version is compatible with other requirements. This could take a while.
> ERROR: Cannot install None, kscale-sim-library and kscale-sim-library[dev]==0.1.0 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     kscale-sim-library 0.1.0 depends on numpy==1.19.5
>     matplotlib 3.3.4 depends on numpy>=1.15
>     tensorboard 2.14.0 depends on numpy>=1.12.0
>     kscale-sim-library[dev] 0.1.0 depends on numpy==1.19.5
>     kscale-sim-library[dev] 0.1.0 depends on numpy==1.24.4; extra == "dev"
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip to attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
> make: *** [Makefile:51: install-dev] Error 1
i know that running `make install `allows the training to work, but `make install-dev` is still required for evaluation.

**Comment by budzianowski** [comment]
Thanks for the patience. This should be fixed with https://github.com/kscalelabs/sim/pull/125
